# Generated by Django 6.0.5 on 2026-06-03 11:27

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeCours', models.CharField(editable=False, max_length=30, verbose_name='code du cours')),
                ('intitule', models.CharField(max_length=200, verbose_name='intitulé du cours')),
                ('volumeHoraire', models.CharField(blank=True, max_length=100, verbose_name='volume horaire')),
            ],
            options={
                'verbose_name': 'cours',
                'verbose_name_plural': 'cours',
                'ordering': ['codeCours', 'intitule'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('niveau', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'option',
                'verbose_name_plural': 'options',
                'ordering': ['niveau', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='UE',
            fields=[
                ('codeUE', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='code UE')),
                ('intituleUE', models.CharField(max_length=200, verbose_name='intitulé UE')),
            ],
            options={
                'verbose_name': 'UE',
                'verbose_name_plural': 'UE',
                'ordering': ['codeUE'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('CD', 'Chef de département'), ('ENSEIGNANT', 'Enseignant'), ('ETUDIANT', 'Étudiant')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='emploi_du_temps.option', verbose_name='option de l’étudiant')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CD',
            fields=[
            ],
            options={
                'verbose_name': 'chef de département',
                'verbose_name_plural': 'chefs de département',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emploi_du_temps.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
            ],
            options={
                'verbose_name': 'enseignant',
                'verbose_name_plural': 'enseignants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emploi_du_temps.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
            ],
            options={
                'verbose_name': 'étudiant',
                'verbose_name_plural': 'étudiants',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('emploi_du_temps.utilisateur',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Creneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi'), ('SAMEDI', 'Samedi')], max_length=20, verbose_name='jour')),
                ('heureDebut', models.TimeField(verbose_name='heure de début')),
                ('heureFin', models.TimeField(verbose_name='heure de fin')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.cours', verbose_name='cours')),
                ('enseignant', models.ForeignKey(limit_choices_to={'role': 'ENSEIGNANT'}, on_delete=django.db.models.deletion.PROTECT, related_name='creneauxEnseignes', to=settings.AUTH_USER_MODEL, verbose_name='enseignant')),
            ],
            options={
                'verbose_name': 'créneau',
                'verbose_name_plural': 'créneaux',
                'ordering': ['jour', 'heureDebut'],
            },
        ),
        migrations.CreateModel(
            name='Conflit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('dateDetection', models.DateTimeField(auto_now_add=True)),
                ('creneau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conflits', to='emploi_du_temps.creneau')),
            ],
            options={
                'verbose_name': 'conflit',
                'verbose_name_plural': 'conflits',
                'ordering': ['-dateDetection'],
            },
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semaine', models.DateField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié'), ('ARCHIVE', 'Archivé')], default='BROUILLON', max_length=20)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateModification', models.DateTimeField(auto_now=True)),
                ('datePublication', models.DateTimeField(blank=True, null=True)),
                ('creePar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emploisDuTempsCrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'emploi du temps',
                'verbose_name_plural': 'emplois du temps',
                'ordering': ['-semaine'],
                'unique_together': {('semaine',)},
            },
        ),
        migrations.AddField(
            model_name='creneau',
            name='emploiDuTemps',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='emploi_du_temps.emploidutemps', verbose_name='emploi du temps'),
        ),
        migrations.AddField(
            model_name='creneau',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.option', verbose_name='option'),
        ),
        migrations.AddField(
            model_name='cours',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='emploi_du_temps.option', verbose_name='option'),
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('site', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'salle',
                'verbose_name_plural': 'salles',
                'ordering': ['site', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('site', 'nom'), name='salle_unique_par_site')],
            },
        ),
        migrations.AddField(
            model_name='creneau',
            name='salle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creneaux', to='emploi_du_temps.salle', verbose_name='salle'),
        ),
        migrations.AddField(
            model_name='cours',
            name='ue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='emploi_du_temps.ue', verbose_name='UE'),
        ),
        migrations.AddConstraint(
            model_name='creneau',
            constraint=models.CheckConstraint(condition=models.Q(('heureDebut__lt', models.F('heureFin'))), name='creneau_heure_debut_avant_fin'),
        ),
    ]
