# Generated by Django 5.2 on 2026-06-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='status',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
    ]
