# Generated by Django 5.2 on 2026-06-12 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0004_cours_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='emploi_du_temps.option', verbose_name='option principale'),
        ),
    ]
