# Generated by Django 5.2 on 2026-07-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emploi_du_temps', '0008_merge_0005_alter_cours_option_0007_recalculer_niveaux'),
        ('emploi_du_temps', '0008_supprimer_comptes_etudiants'),
    ]

    operations = [
    ]
